### ISSUE TITLE
[Desktop] Benefits section

### ISSUE THREAD

**Issue by xReady45** [UnlockdFinance/unlockd-landing-page#32]
https://drive.google.com/file/d/1yIAuDSHFlqsK1tOPL7fwJf95idDF2zdh/view?usp=drive_link

**Comment by shaheerhashim10** [comment]
- [ ] Adjust the Gradient shade below the benefits title
- [ ] The text of Benefits should be smaller
- [ ] Make the font of the paragraph smaller
- [ ] Add gradient in the Benefits box. Bottom left and top right
- [ ] Adjust the ratio of the Benefits box

**Comment by shaheerhashim10** [comment]
@xReady45  I have resolved 3 issues from the video that are ticked in the above comment.  
Please review them and let me know your feedback.

**Comment by shaheerhashim10** [comment]
@xReady45 all the above-mentioned issues are resolved. Please review and give feedback.

**Comment by xReady45** [comment]
My only issue here, is that the description text looks like it's medium instead of regular, other than that, good to go.

**Comment by shaheerhashim10** [comment]
> My only issue here, is that the description text looks like it's medium instead of regular, other than that, good to go.

@xReady45 are you talking about the font-weight or the font-size of the Benefits description?

**Comment by xReady45** [comment]
Within the Montserrat font, we are using Montserrat Medium for that text and I think we should use Montserrat Regular instead

**Comment by shaheerhashim10** [comment]
> Within the Montserrat font, we are using Montserrat Medium for that text and I think we should use Montserrat Regular instead

We are using the Montserrat Regular font.

**Comment by xReady45** [comment]
Let it be then, maybe the web version is different than the desktop version.

**Comment by shaheerhashim10** [comment]
> Let it be then, maybe the web version is different than the desktop version.

Okay. You can close the issue now.
